FROM python:3.10.8-slim-bullseye
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /backend

COPY . .

RUN pip install -r requirements.txt --no-cache-dir

CMD python manage.py runserver 0.0.0.0:8000 
# EXPOSE 8000