# Generated by Django 4.2.1 on 2023-05-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast', '0002_student_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-first_name'], 'verbose_name': 'Student'},
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='--'),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
